AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0
Metrics/AbcSize:
  Max: 16
Metrics/BlockLength:
  Max: 80
Metrics/CyclomaticComplexity:
  Max: 3
Metrics/MethodLength:
  Max: 15
Naming/MethodParameterName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
