AllCops:
    NewCops: enable
    TargetRubyVersion: 2.0
Metrics/AbcSize:
    Max: 23
Metrics/BlockLength:
    Max: 37
Metrics/CyclomaticComplexity:
    Max: 6
Metrics/MethodLength:
    Max: 16
Naming/MethodParameterName:
    Enabled: false
Metrics/PerceivedComplexity:
    Max: 6
Naming/VariableNumber:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Style/HashSyntax:
    Enabled: false
