name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
                ruby-version:
                    [2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: ${{ matrix.ruby-version }}

            - name: Run bundle install (legacy)
              if: matrix.ruby-version != 2.0 && matrix.ruby-version != 2.1 && matrix.ruby-version != 2.2
              run: |
                  gem install bundler
                  bundle install

            - name: Run bundle install
              if: matrix.ruby-version == 2.0 || matrix.ruby-version == 2.1 || matrix.ruby-version == 2.2
              run: |
                  gem install bundler -v '1.17.3'
                  bundle install

            - name: Run tests
              run: |
                  bundle exec rspec

            - name: Upload coverage to Codecov
              if: matrix.os == 'ubuntu-latest' && matrix.ruby-version == 3.3
              uses: codecov/codecov-action@v3

    format-markdown:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Format Markdown with markdownlint
              run: |
                  npm install -g markdownlint-cli
                  markdownlint --disable MD013 --fix . --ignore CODE_OF_CONDUCT.md
                  git add -A
                  git diff --cached --exit-code

    format-ruby:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3

            - name: Install rubocop
              run: |
                  gem install rubocop

            - name: Format Ruby with rubocop
              run: |
                  rubocop
