name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
                ruby-version:
                    ["2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]
                exclude:
                    - { os: macos-latest, ruby-version: "2.4" }
                    - { os: macos-latest, ruby-version: "2.5" }
                include:
                    - { os: macos-13, ruby-version: "2.4" }
                    - { os: macos-13, ruby-version: "2.5" }
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: ${{ matrix.ruby-version }}
                  bundler: "none"

            - name: Run bundle install
              run: |
                  gem install bundler:2.3.27
                  bundle _2.3.27_ install

            - name: Run tests
              run: |
                  bundle _2.3.27_ exec rspec -r spec_helper

            - name: Upload coverage to Coveralls
              if: matrix.os == 'ubuntu-latest' && matrix.ruby-version == '3.4'
              uses: coverallsapp/github-action@v2

    format-markdown:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Format Markdown with markdownlint
              run: |
                  npm install -g markdownlint-cli
                  markdownlint --disable MD013 MD033 --fix . --ignore CODE_OF_CONDUCT.md
                  git add -A
                  git diff --cached --exit-code

    format-ruby:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3

            - name: Install rubocop
              run: |
                  gem install rubocop
                  gem install rubocop-rspec

            - name: Format Ruby with rubocop
              run: |
                  rubocop
